### ISSUE TITLE
Select Publication - Please change color (TFS 36125)

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance-AL-Tokenization#1]
Please change colors to match Michigan.
![colors](https://user-images.githubusercontent.com/25616655/27958902-269e4264-62f3-11e7-9532-9472c3541365.PNG)

**Comment by mkoza178** [comment]
We have a work item out there for this. Attaching to ticket.

**Comment by mkoza178** [comment]
Check now, this is fixed.
