### ISSUE TITLE
User agreement links in New Start WorkFlow (TFS 36203)

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance-AL-Tokenization#3]
Can we make this look like it does in the common code (Syracuse....). User Agreement is in orange which let's people know they can click on it. 
![birthday in new start](https://user-images.githubusercontent.com/25616655/27966181-52c35622-630c-11e7-9a6c-826f6f08eb38.PNG)

**Comment by mkoza178** [comment]
Work item created.

**Comment by mkoza178** [comment]
Ready to test. Did not make the same color as Syr because it's a css style and color scheme but we underlined to make it visible they could be clicked.
